global:
  scrape_interval: 10s
  evaluation_interval: 5s

rule_files:
 - "/etc/prometheus/prometheus-rules.yml"

scrape_configs:
  - job_name: "silly-server"
    static_configs:
    - targets: ["host.docker.internal:3030"]
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
